
name: pygbag_build
on: [workflow_dispatch]


jobs:
  build-pygbag:
    name: Build for Emscripten pygbag runtime
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v2
      # with:
      #   path: main
    - name: Checkout reveal.js
      uses: actions/checkout@v2
      with:
        repository: hakimel/reveal.js
        path: reveal.js
    - name: Build with pygbag
      run: |
            python -m pip install pygbag
            mv $GITHUB_WORKSPACE/src/*.py $GITHUB_WORKSPACE/
            python -m pygbag --build $GITHUB_WORKSPACE/main.py
    - name: Move quickstart.html & reveal.js into build/web
      run: |
            mkdir -p $GITHUB_WORKSPACE/build/web
            cd $GITHUB_WORKSPACE/reveal.js
            rm README.md index.html demo.html
            cd $GITHUB_WORKSPACE
            mv reveal.js/*  build/web/
            mv doc/*        build/web/
            mv README.md    build/web/
            cd $GITHUB_WORKSPACE/build/web/
            mv index.html demo.html
    - name : "Upload to GitHub pages branch gh-pages"
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        branch: gh-pages
        folder: build/web